### ISSUE TITLE
This

### ISSUE THREAD

**Issue by EpicGamer2003** [filveith/BetterDiscord-Spotify-Lyrics-Status#1]
![image](https://user-images.githubusercontent.com/53325601/140244825-3038eff4-308b-407b-bc8b-8a30c30e1b35.png)

**Comment by filveith** [comment]
Thanks for trying to use it, but unfortunately the API I was using got shutdown and for the moment the owner is not answering me. So for the moment the plugin is sadly deprecated :((

**Comment by EpicGamer2003** [comment]
Alrighto

**Comment by filveith** [comment]
@EpicGamer2003 
Hi, if you want the plugin works now :)
