### ISSUE TITLE
The plugin doesn't seem to work

### ISSUE THREAD

**Issue by Begnom** [filveith/BetterDiscord-Spotify-Lyrics-Status#10]
I have music on, and spotify connected to my discord account but it doesn't seem to work at all.

**Comment by Clowncuck** [comment]
I assume the plugin should work with any Spotify song that has the lyrics already available on the app, but the only song with lyrics that seems to work is Never Gonna Give You Up.

**Comment by filveith** [comment]
Hi @Begnom , 

I also have this bug at the moment and I really don't know how to fix it. Maybe you can try running discord on another computer, logout and log back into your spotify account on discord and maybe reinstall discord + better discord

Sorry that I don't have a real solution for it.

**Comment by filveith** [comment]
Hi @Clowncuck ,

We can't use the lyrics from spotify so we use an api that doesn't as much lyrics as spotify.
But a lot of songs should work

Do you have an example song that doesn't work ? (So I can check if it is a plugin problem or if the API just doesn't have the song)

**Comment by Clowncuck** [comment]
@filveith 

Sun and The Moon - Freddie Sunshine
https://open.spotify.com/track/1Jm2bIfJzbGXiEsARCGaye?si=955b9eefa34a4139

Sightsee - Naethan Apollo, Claudia Melo
https://open.spotify.com/track/4oE4uLNVZWTrBCnWPUhxhj?si=9422c0e62a2f4b21

**Comment by filveith** [comment]
Okay, I checked, and the API doesn't have the lyrics for it, sorry.
The lyrics that come from the API are very random, but at this moment it is the best API I could find.

If you wanna check here are some song that work:
Freeze Corleone - Desiigner
https://open.spotify.com/track/50H3jnyW9MJRsdWRLsud79?si=0da43278a64c4616

Purple disco - Devil in Me
https://open.spotify.com/track/41rOnZXVg3cLacziEBgkpW?si=d851cd5479d244cb

https://open.spotify.com/track/0upFohXrGxIIAjyaJmCkMU?si=41f596483bb4425f
