### ISSUE TITLE
Settings are undefined after update

### ISSUE THREAD

**Issue by filveith** [filveith/BetterDiscord-Spotify-Lyrics-Status#15]
This happens when the plugin is update, setting all the parameters to undefined

![image](https://user-images.githubusercontent.com/82966162/175012203-1c6e5066-1a9b-4e7a-aa47-e65bf55bbf8f.png)

But JSON file is good : 
![image](https://user-images.githubusercontent.com/82966162/175012448-d76347d2-9647-4088-a23c-ab6898f400a3.png)

**Comment by unguest** [comment]
Same here, running on Mac OS.

**Comment by patrickzhou1234** [comment]
I also bump this happening on windows.
