### ISSUE TITLE
Better Discord crashes when lyrics is displayed

### ISSUE THREAD

**Issue by Hazri45** [filveith/BetterDiscord-Spotify-Lyrics-Status#16]
I have to disable the plugin to use Spotify and discord at the same time because better discord keeps crashing when I start playing a song that has lyrics available to change the status

**Comment by filveith** [comment]
Hi,

What song were you listening to when it crashed ?
I am currently using the plugin with the latest version of discord and no crashes.

**Comment by Hazri45** [comment]
> Hi,
> 
> What song were you listening to when it crashed ? I am currently using the plugin with the latest version of discord and no crashes.

full stop by Jeremy Zucker. i will keep experimenting with other songs too when i can

**Comment by filveith** [comment]
So I tried the song, and it worked on my side. Maybe you can reload discord (ctrl + R), this helps sometimes.
And are you still having the bug ?

![image](https://user-images.githubusercontent.com/82966162/177010619-dbc619d3-702f-4ba9-8bec-897a783520d5.png)

**Comment by Hazri45** [comment]
i tried it with same song and now the lyrics doesn't even appear on status

**Comment by Hazri45** [comment]
> So I tried the song, and it worked on my side. Maybe you can reload discord (ctrl + R), this helps sometimes. And are you still having the bug ?
> 
> ![image](https://user-images.githubusercontent.com/82966162/177010619-dbc619d3-702f-4ba9-8bec-897a783520d5.png)

it crashed at the most inconvenient time causing me to lost my FIFA match because it alt-tab you immediately omg

**Comment by filveith** [comment]
> i tried it with same song and now the lyrics doesn't even appear on status

Four days ago the source used for the lyrics was down, thus resulting in no lyrics being displayed at all 

> > So I tried the song, and it worked on my side. Maybe you can reload discord (ctrl + R), this helps sometimes. And are you still having the bug ?
> > ![image](https://user-images.githubusercontent.com/82966162/177010619-dbc619d3-702f-4ba9-8bec-897a783520d5.png)
> 
> it crashed at the most inconvenient time causing me to lost my FIFA match because it alt-tab you immediately omg

I am sorry that it crashed during your game.
At the moment, I have no idea why it is crashing this many times for you,
What version of Spotify-Lyrics-Status have you installed ? 
What are the other plugins you have installed ? (I know that some plugins can interfere with this plugin)
And what is the version of you discord ?

**Comment by Hazri45** [comment]
full stop by jeremy zucker
