### ISSUE TITLE
Not every sont that has lyrics shot on status 

### ISSUE THREAD

**Issue by MmGaboimM** [filveith/BetterDiscord-Spotify-Lyrics-Status#17]
I tried to play rickroll and it works but when i try to play my own music it doesn't display anything

https://user-images.githubusercontent.com/96992621/178108013-c73f65af-f659-4208-81a7-442d0eb1febd.mp4

**Comment by filveith** [comment]
Hi,

Thanks for the video with the issue. 
We are not using the lyrics that are displayed on Spotify because we don't have the right to use it at the moment.
We are using another source for the lyrics that is called api.textyl.co, and this service doesn't have as many lyrics as Spotify.
