### ISSUE TITLE
Plugin does not update the status anymore.

### ISSUE THREAD

**Issue by GooseBrother** [filveith/BetterDiscord-Spotify-Lyrics-Status#19]
Tried with multiple songs, which have worked before. Reinstall betterdiscord and the plugin, restarted and reloaded discord (obviously) and the plugin does not work. If I change my status to something and then play a song it removes my status at all, but does not update it with lyrics.

**Comment by filveith** [comment]
Hi,
It works on my side, I am using Windows 11 and discord + better discord are on their latest version.
Before testing it, I repaired better-discord (using the better discord installer). Once the repairing process was finished, I started discord, updated all the plugins and reloaded discord (ctrl + R).
I don't know how to help you at the moment.
