### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by GooseBrother** [filveith/BetterDiscord-Spotify-Lyrics-Status#23]
![image](https://user-images.githubusercontent.com/51734900/185963148-b23efe7c-00ec-40d4-878d-a383e443f9c7.png)

**Comment by filveith** [comment]
Hi, thanks for the report,
Is this still happening, or was this a one time thing ?

**Comment by GooseBrother** [comment]
Hello, it was happening for 2 days and sometimes still happens after a
plugin update. Right now it's all good.
