### ISSUE TITLE
Could not interpret "{}" as string.

### ISSUE THREAD

**Issue by Jck0day** [filveith/BetterDiscord-Spotify-Lyrics-Status#24]
Hey I love this plugin because at a moment it worked and it was really cool but now it show some toasts again saying "Could not interpret "{}" as string." with the same songs :/
Do you have an idea of what can cause this ?

**Comment by filveith** [comment]
Hi thanks ;))
Not really, this can be a lot of things, but is it working now or do you still have these messages ?
Was this happening with all the songs, or only certain ones ?
Sometimes a little reload of discord can be enough to fix this type of problems

**Comment by Jck0day** [comment]
> Hi thanks ;)) Not really, this can be a lot of things, but is it working now or do you still have these messages ? Was this happening with all the songs, or only certain ones ? Sometimes a little reload of discord can be enough to fix this type of problems

Since your last update I do not have the error but now it simply don't change the status :(
If I reload the plugin while I'm playing a music it will put the no lyrics status value. But it will disapear when the music is changed, it's doing this with all musics even after some discord restarts...

**Comment by filveith** [comment]
I'm happy to hear that the update fixed the problem. Yeah sadly we can't do anything about it at the moment :((
