### ISSUE TITLE
what are the requirements

### ISSUE THREAD

**Issue by MagonYT** [filveith/BetterDiscord-Spotify-Lyrics-Status#25]
i accidentally clicked no

**Comment by filveith** [comment]
The easiest way to download the missing plugins would be to deactivate and re-activate Spotify-Lyrics-Status. This should again show you the prompt to download the required plugins.

If this doesn't work, the required plugin is the BDFDB from DevilBro ([link](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Library/) to the repository) and you just need to download the file called **0BDFDB.plugin.js**.

Or, you can click on the download button (see image down below) and copy the downloaded file into the better discord plugin folder. To be sure that everything is working, reload discord by pressing Ctrl + R
![Download plugin](https://user-images.githubusercontent.com/82966162/186499941-1408a402-b4a7-4692-9093-4901d634dc55.png)
