### ISSUE TITLE
Dont Work, Auth Error

### ISSUE THREAD

**Issue by olebohmbach** [filveith/BetterDiscord-Spotify-Lyrics-Status#31]
![image](https://user-images.githubusercontent.com/77053238/201540942-5ab357a5-531d-43a6-836f-fb3ab9d9a87a.png)

**Comment by DarkModeMemer** [comment]
same for me, tried using my spotify and discord's auth tokens

**Comment by filveith** [comment]
Hi, thanks for using the plugin, but we decided to deprecate it.
Fixing it would require a lot of work and additional programs to be downloaded.

Thanks for using it :))
